# Generated by Django 5.1.3 on 2026-02-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicecategory_alter_servicerequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.servicecategory",
            ),
        ),
    ]
